name: Keepalive

on:
  schedule:
    - cron: "0 */4 * * *" # check every 8 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-keepalive:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ vars.PORTFOLIO_URL }}
      STATE_FILE: .github/keepalive.json
      LOG_FILE: docs/keepalive-log.md
      DEFAULT_BRANCH: main
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Run keepalive.py
        run: python3 keepalive.py
